spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: goblin-payment
              uri: http://localhost:8081
            - id: goblin-assistant
              uri: http://localhost:8082
            - id: goblin-game-engine
              uri: http://localhost:8083