server:
  port: 8080

spring:
  application:
    name: goblin-gateway
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URI:http://localhost:8094/realms/goblin-dev-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8094/realms/goblin-dev-realm/protocol/openid-connect/certs}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: Retry
              args:
                retries: 3
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 1s
          routes:
            - id: goblin-payment
              uri: ${GOBLIN_PAYMENT:http://localhost:8081}
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1
            - id: goblin-assistant
              uri: ${GOBLIN_ASSISTANT:http://localhost:8082}
              predicates:
                - Path=/assistant/**
              filters:
                - StripPrefix=1
            - id: goblin-game-engine
              uri: ${GOBLIN_GAME_ENGINE:http://localhost:8083}
              predicates:
                - Path=/game-engine/**
              filters:
                - StripPrefix=1

management:
  otlp:
    metrics:
      export:
        enabled: false
        url: ${GOBLIN_OTLP:http://localhost:4318/v1/metrics}

logging:
  level:
    org.springframework.security: DEBUG